dywee_news_table:
    path:     /admin6833/news/table/{page}
    defaults: { _controller: DyweeNewsBundle:News:table, page:1 }
    requirements:
        page: \d*

dywee_news_add:
    path:     /admin6833/news/add
    defaults: { _controller: DyweeNewsBundle:News:add }

dywee_news_update:
    path:     /admin6833/news/update/{id}
    defaults: { _controller: DyweeNewsBundle:News:update }
    requirements:
        id: \d+

dywee_news_delete:
    path:     /admin6833/news/delete/{id}
    defaults: { _controller: DyweeNewsBundle:News:delete }
    requirements:
        id: \d+

dywee_news_view:
    path:     /news/{data}
    defaults: { _controller: DyweeNewsBundle:News:view }