<?php

namespace Dywee\NewsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NewsletterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
    public function myFind($website, $limit = null)
    {
        $qb = $this->createQueryBuilder('n')
            ->select('n')
            ->orderBy('n.publicationDate', 'desc')
            ->leftJoin('n.image', 'i')
            ->addSelect('i')
            ->where('n.website = :website')
            ->setParameter('website', $website);

        if(is_numeric($limit))
            $qb->setMaxResults($limit);

        $query = $qb->getQuery();

        return $query->getResult();
    }
}
